# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TechnicalTestMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TechnicalTestMVVM
  pod 'Alamofire' , '5.6.4'
  pod 'AlamofireImage', '~> 4.1'

  target 'TechnicalTestMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechnicalTestMVVMUITests' do
    # Pods for testing
  end

end
